version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stock-postgres
    restart: unless-stopped
    networks:
      - stock_trading_network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-stocktrading}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-stocktrading}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  stock_trading_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
