version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - stock_trading_network
    volumes:
      - ../db/conf.d:/etc/mysql/conf.d
      - ../db/data:/var/lib/mysql
      - ../db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  banking-service:
    image: choco-pay-banking-service:1.0.0
    networks:
      - chocopay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/choco_banking?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_MVC_CONVERTERS_PREFERRED-JSON-MAPPER=gson
      - SPRINGDOC_SWAGGER-UI_PATH=/swagger-ui.html
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM.CHOCOPAY.MEMBERSHIP=DEBUG

  membership-service:
    image: choco-pay-membership-service:1.0.2
    networks:
      - chocopay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/choco_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_MVC_CONVERTERS_PREFERRED-JSON-MAPPER=gson
      - SPRINGDOC_SWAGGER-UI_PATH=/swagger-ui.html
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM.CHOCOPAY.MEMBERSHIP=DEBUG

  money-service:
    image: choco-pay-money-service:1.0.0
    networks:
      - chocopay_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/choco_money?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_MVC_CONVERTERS_PREFERRED-JSON-MAPPER=gson
      - SPRINGDOC_SWAGGER-UI_PATH=/swagger-ui.html
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM.CHOCOPAY.MONEY=DEBUG

networks:
  chocopay_network:
    driver: bridge
