version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: stock-timescaledb
    networks:
      - stock_trading_network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-stocktrading}
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./transaction-service/src/main/resources/sql/init-timescaledb.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  stock_trading_network:
    driver: bridge

volumes:
  timescale_data:
    driver: local
